### ISSUE TITLE
Issue with ULX

### ISSUE THREAD

**Issue by Shaknunic** [Alf21/ttt2-util_animations#1]
There's a issue with this script and ulx modules, i dunno the source of the problem, but every time i put this, this error show up when someone joins the server:

```
[ERROR] addons/ulx+ulib-beta/lua/ulx/modules/sh/cc_pgag.lua:72: attempt to index a string value with bad key ('GetPData' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:297
    3. fn - addons/ulx+ulib-beta/lua/ulx/modules/sh/cc_pgag.lua:72
     4. Run - addons/ulx+ulib-beta/lua/ulib/shared/hook.lua:109
      5. func - addons/[ttt]_ttt2/lua/animations/cl_init.lua:11
       6. unknown - lua/includes/extensions/net.lua:32
```

**Comment by Alf21** [comment]
Hmm... it could be possible that this ULX module also uses PlayerAuthed hook. I will rename it, maybe it will fix the bug

**Comment by Alf21** [comment]
@Shaknunic Please test it and tell me whether it is fixed and the animations still work. I don't know whether it works because it's untested and maybe gmod isn't able to handle the player object at the time I try to get it.

Currently I'm working on a huge update of TTT2 and my test server is filled with errors at this state of development (debugging, hints, etc.).

**Comment by Shaknunic** [comment]
All right! I will be testing, after i fix all the bugs in my server, yeah i've been doing that for 3 days now 👍

**Comment by Shaknunic** [comment]
Now it shows this error:

```
[ERROR] ttt2/lua/animations/client/libs/web_image.lua:68: attempt to call method 'SteamID64' (a nil value)
  1. fn - addons/[ttt]_ttt2/lua/animations/client/libs/web_image.lua:68
   2. Run - addons/ulx+ulib-beta/lua/ulib/shared/hook.lua:109
    3. func - addons/[ttt]_ttt2/lua/animations/cl_init.lua:10
     4. unknown - lua/includes/extensions/net.lua:32
```

**Comment by Alf21** [comment]
Yea that's what I expected... Gmod is still a little bit broken / incontinues ^^ I will fix this... At this state, the player obj is not initialized. But i wasn't wrong lol ( http://wiki.garrysmod.com/page/Player/SteamID64 )

**Comment by Alf21** [comment]
Alright, same as yesterday. Pushed a new fix. Hopefully i didn't made any mistakes

**Comment by Shaknunic** [comment]
Yeah now it's fixed, no errors in the console, thank you.
