### ISSUE TITLE
Innocent Animation Bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Alf21/ttt2-util_animations#5]
Innocent animation doesn't work properly, Also the Shinigami has the same bug 
https://youtu.be/x4uUyBGSWVw
I noticed this bug a long time ago but I always forgot to report it
I also noticed that, if you use the ulx command "force innocent" the animation works fine for some reason

No error in client/server console

**Comment by TimGoll** [comment]
This is because internally in TTT everyone is innocent, event without a role. Therefore the roleChange hook won't be called. This will be changed in a coming update by introducing a new rolestate.

**Comment by ThePlatinumGhost** [comment]
okey thanks

**Comment by mexikoedi** [comment]
This should be fixed by now. I think this was fixed when the update with ROLE_NONE was published.

**Comment by saibotk** [comment]
Can someone verify this please?

**Comment by TimGoll** [comment]
It is fixed, yes
