### ISSUE TITLE
Client side option to hide animation

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Alf21/ttt2-util_animations#7]
Add the client side option to disable the initial animation
I say this for a user of my server who usually streams and to avoid ghosting he hides the writing with the role at the bottom left, but he cannot hide the initial animation

if there is already a similar option, tell me and close the post

**Comment by TimGoll** [comment]
This is probably something that can be easily added once the new vgui rework is done! :)

**Comment by ThePlatinumGhost** [comment]
I close this in favor to https://github.com/TTT-2/TTT2/issues/534
